# Generated by Django 3.2.2 on 2021-05-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Game name')),
                ('event_date', models.DateTimeField(verbose_name='Game date')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventBet', models.CharField(max_length=200, verbose_name='pari')),
                ('dollars', models.IntegerField(verbose_name='bet amount')),
                ('date_added', models.DateTimeField(verbose_name='bet date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freebets.event')),
            ],
        ),
    ]
