# Generated by Django 3.2.2 on 2021-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200, verbose_name='login')),
                ('cash', models.IntegerField()),
                ('registration', models.DateTimeField(verbose_name='Registration date')),
            ],
        ),
    ]
