# Generated by Django 3.2.2 on 2021-05-21 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idx',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
