# Generated by Django 3.2.2 on 2021-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freebets', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='event',
            new_name='login',
        ),
    ]
