# Generated by Django 3.2.2 on 2021-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebets', '0004_event_event_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cash_to_first_team',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='cash_to_second_team',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
