# Generated by Django 3.2.2 on 2021-05-13 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebets', '0005_auto_20210512_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='dollars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='bet amount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cash_to_first_team',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='cash_to_second_team',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_result',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='event result'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
